`---
- hosts: 192.168.56.103
  become: true
  tasks:
   - name: install wget
     yum:
       name: wget
       state: present
   - name: install java
     yum:
       name: java-17-openjdk
       state: present
   - name: add repo
     command: wget -O /etc/yum.repos.d/jenkins.repo \ https://pkg.jenkins.io/redhat-stable/jenkins.repo
   - name: add key
     rpm_key:
       key: https://pkg.jenkins.io/redhat-stable/jenkins.io-2023.key
   - name: install jenkins
     yum: 
       name: jenkins
       state: present
   - name: start service
     service:
       name: jenkins
       state: started
   - name: init password jenkins
     shell: cat /var/lib/jenkins/secrets/initialAdminPassword
     changed_when: false
     register: result
   - name: print init password jenkins
     debug:
       var: result.stdout  `   

    