---
- hosts: 192.168.56.6
  become: true
  tasks:
 

  - name: uninstall openjdk
    yum:
     name: java-1.8.0-openjdk
     state: absent
    
  - name: uninstall jenkins
    yum:
     name: jenkins
     state: absent
    
 
    
  - name: Remove Jenkins folder
    shell: rm -rf  /var/lib/jenkins
    changed_when: false
    register: result
    
  - name: print init password jenkins
    debug:
     var: result.stdout