---
- hosts: 192.168.56.15
  become: true
  tasks:
    - name: Install list of packages
      apt: name='{{item}}' state=present
      with_items:
       - apache2
       - wget
       - vim
       - zip
       - unzip  