---
- hosts: all
  become: true
  tasks:
    - name: Install Java
      apt:
        name: openjdk-17-jre-headless
        state: present
    - name: add tomcatuser
      user:
        name: tomcat
        shell: /sbin/nologin
    - name: get_installer
      get_url:
        url: https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.97/bin/apache-tomcat-9.0.97.zip
        dest: /tmp/
    - name: copy
      copy:
        src: /tmp/apache-tomcat-9.0.97.tar.gz
        dest: /usr/local/
        remote_src: yes
    - name: install
      unarchive:
        src: /usr/local/apache-tomcat-9.0.97.tar.gz
        dest: /usr/local
        remote_src: yes
    - name: Change file ownership, group and permissions
      file:
        path: /usr/local/apache-tomcat-9.0.97
        owner: tomcat
        group: tomcat
        recurse: yes
        state: directory
    - name: make tomcat symbolic
      file:
        src: /usr/local/apache-tomcat-9.0.97
        dest: /usr/local/tomcat7
        owner: tomcat
        group: tomcat
        state: link
    - name: make tomcat.service
      file:
        path: /etc/systemd/system/tomcat.service
        state:  touch
    - name: edit tomcat.service
      blockinfile:
        dest: /etc/systemd/system/tomcat.service
        insertafter:
        block: |
          [Unit]
          Description = Apache Tomcat 7
          After = syslog.target network.target
          [Service]
          User = tomcat
          Group = tomcat
          Type = oneshot
          PIDFile =/usr/local/apache-tomcat-9.0.97/tomcat.pid
          RemainAfterExit = yes
          ExecStart =/usr/local/apache-tomcat-9.0.97/bin/startup.sh
          ExecStop =/usr/local/apache-tomcat-9.0.97/bin/shutdown.sh
          ExecReStart =/usr/local/apache-tomcat-9.0.97/bin/shutdown.sh;/usr/local/apache-tomcat-9.0.97/bin/startup.sh
          [Install]
          WantedBy = multi-user.target
    - name: chmod 755 tomcat.service
      file:
        path: /etc/systemd/system/tomcat.service
        mode:  0755
    - name: start tomcat
      systemd:
        name: tomcat.service
        state: started
        daemon_reload: yes
        enabled: yes